### ISSUE TITLE
May I ask where the llava model needs to be placed if downloaded manually?

### ISSUE THREAD

**Issue by KennyChan3389** [christian-byrne/img2txt-comfyui-nodes#2]
May I ask where the llava model needs to be placed if downloaded manually?
Now there is an error message:
<img width="1330" alt="03b0a8f81a2c6af2535247e6a3a1fc40" src="https://github.com/christian-byrne/img2txt-comfyui-nodes/assets/155774773/0861cdca-f2d4-4a90-90c5-6cc70d1a38d1">

My transformers= 4.38.1
What is the reason for this error?

**Comment by christian-byrne** [comment]
For the error, try installing the `bitsandbytes` package:

```bash
pip install bitsandbytes
```

For model locations, the node uses the Huggingface cache system. From [their documentation](https://huggingface.co/docs/transformers/main/en/installation#cache-setup):

Pretrained models are downloaded and locally cached at: ~/.cache/huggingface/hub. This is the default directory given by the shell environment variable TRANSFORMERS_CACHE. On Windows, the default directory is given by C:\Users\username\.cache\huggingface\hub. You can change the shell environment variables shown below - in order of priority - to specify a different cache directory:

- Shell environment variable (default): HUGGINGFACE_HUB_CACHE or TRANSFORMERS_CACHE.
- Shell environment variable: HF_HOME.
- Shell environment variable: XDG_CACHE_HOME + /huggingface.

**Comment by KennyChan3389** [comment]
It has been checked and the download has started, please write the dependency packages into the requirements.txt file

**Comment by christian-byrne** [comment]
I'm not sure if bitsandbytes is compatible with Windows yet. If not I will add a check to not use the package if user is on Windows. It is only necessary for 4bit quantization which improves memory usage.

**Comment by christian-byrne** [comment]
It seems [bitsandbytes is supported on windows as of version 0.43.0](https://github.com/TimDettmers/bitsandbytes/blob/b891f80ba514833f41f0e9226983b02a9fb5c44b/CHANGELOG.md). 

Commit f111f8d adds `bitsandbytes>=0.43.0` to requirements.txt to resolve the missing dependency and ensure Windows support. 

Thank you for pointing out this error.

**Comment by christian-byrne** [comment]
Commit 6038415 adds documentation for model locations in HF cache and manual installation. 

Unfortunately, HF system still would require some manual folder and config creation to use a manually downloaded model. And many custom nodes do not use the cache system. Considering adding a model loader or model path option in the UI. Closing the issue for now. Thanks again for the input.

**Comment by KennyChan3389** [comment]
Can't these models be put together with the Comfyui/models directory?

**Comment by christian-byrne** [comment]
Using Hugging Face (HF) Hub to download/manage models is generally much more efficient and reliable.

It's not always feasible with Stable Diffusion models, as creators often don't make HF repos for them. However, these models are usually singular files, making manual management easier.

Widely used models like BLIP (600k+ downloads) come with additional configuration files and are often updated/versioned. Using HF Hub for these models offers significant benefits: security, version control, convenience, and efficient file management. In particular, leveraging their local caching system is likely faster, more robust, and less prone to bugs than any custom solution by me or other individual developers.

We can configure HF to use the `ComfyUI/models` dir, but that would somewhat defeat the purpose, as the cache should be shared across all custom nodes and even other AI programs used separately from ComfyUI.

If there's something I've missed, please let me know. Any feedback is appreciated. Thanks.
