### ISSUE TITLE
No module named 'src.img_tensor_utils'

### ISSUE THREAD

**Issue by thefirstLeonliao** [christian-byrne/img2txt-comfyui-nodes#5]
Cannot import D:\AI\ComfyUI-aki-v1.3\custom_nodes\img2txt-comfyui-nodes module for custom nodes: No module named 'src.img_tensor_utils'
JSON file 'presets.json' not found.

what should i do？

**Comment by christian-byrne** [comment]
- When did you download this repo? If it was a while ago, you should try re-installing/ pulling.
- If you just downloaded and are having this problem, can you confirm that the file `D:\AI\ComfyUI-aki-v1.3\custom_nodes\img2txt-comfyui-nodes\src\img_tensor_utils.py` exists or not?
- If the file does exist, are you using symlinks at all?

**Comment by jjandnn** [comment]
img2txt_node.py修改为相对路径：：：：：

import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(__file__)))
print(sys.path)  # 添加此行来检查sys.path
from .img_tensor_utils import TensorImgUtils
from .llava_img2txt import LlavaImg2Txt
from .blip_img2txt import BLIPImg2Txt
from .mini_cpm_img2txt import MiniPCMImg2Txt

**Comment by christian-byrne** [comment]
> Modify img2txt_node.py to a relative path:
> 
> import sys import os
> 
> sys.path.append(os.path.dirname(os.path.dirname(**file**))) print(sys.path) # 添加此行来检查sys.path from .img_tensor_utils import TensorImgUtils from .llava_img2txt import LlavaImg2Txt from .blip_img2txt import BLIPImg2Txt from .mini_cpm_img2txt import MiniPCMImg2Txt

3Q fixed in 8a8de75. Appreciate your help
